name: Build and deploy Node.js app to Azure Web App - darkdome-hotsite

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  AZURE_WEBAPP_NAME: 'darkdome-hotsite'
  AZURE_WEBAPP_PACKAGE_PATH: './.next/standalone'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci --legacy-peer-deps --prefer-offline

    - name: Build project
      run: |
        npm run build

    - name: Generate standalone output
      run: |
        rm -rf .next/standalone
        mkdir -p .next/standalone
        cp -R .next/static .next/standalone/.next/
        cp -r public .next/standalone/
        cp -r package*.json .next/standalone/
        cp -r next.config.js* .next/standalone/ || true
        cd .next/standalone && zip -r ../../release.zip ./*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: azure-webapp-package
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: azure-webapp-package
        path: .

    - name: Unzip package
      run: |
        unzip release.zip -d .next/standalone

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_07894C635D2A433690418DAD88B01B25 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AC200A855B3247BFB8B57AFC48EE2347 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF48ACDA51D44EE7B2366D01B1CB1C02 }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
